
[package]
name = "vector-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
hnsw_rs = "0.3.1"
actix-web = "4"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
