version: '3.8'

services:
  vector-engine:
    build:
      context: .
      dockerfile: vector-engine/Dockerfile
    ports:
      - "9000:9000"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - vector-engine

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
