version: "3.8"

services:
  vector-engine:
    build:
      context: .
      dockerfile: vector-engine/Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      VECTOR_ENGINE_URL: http://vector-engine:9000
    ports:
      - "8080:8080"
    depends_on:
      - vector-engine
    restart: unless-stopped
